### ISSUE TITLE
Any plans for Svelte support?

### ISSUE THREAD

**Issue by borsemayur2** [cmorten/luath#1]
It'd be great to have support for svelte and sveltekit

Please enable discussions section to ask questions  over there

**Comment by cmorten** [comment]
Hey @borsemayur2 👋 

The plan is to framework agnostic from the off! With support for any lib provided an appropriate plugin is created and added to config if required.

My immediate priority is to firm up / stabilise so of the core functionality, as well as extracting the core into re-usable middleware so folks can import it into their own servers ( e.g. for SSR usecases, further control etc. ). Following that the likes of Vue, Preact and Svelte are all of interest - just a matter of time can spare!

Very much open to PRs / collab 😄

**Comment by borsemayur2** [comment]
Sounds great. I'm not sure how the implementation could be done for the mentioned features but I'd definitely like to contribute with some guidance.
